(() => {
let data=Guide.load(),dirty=false,previewTimer;
const group=document.querySelector('#group'),field=document.querySelector('#field'),value=document.querySelector('#value'),frame=document.querySelector('#preview');
const groups=[];
const fields=[];
const labels={title:'제목',subtitle:'부제',intro:'표지 소개',annotation:'상단 주석 안내',body:'본문',years:'연도',summary:'한 줄 요약',name:'이름',label:'세부 소속',role:'핵심 역할',image:'이미지 주소',alt:'이미지 설명',age:'나이',job:'직책',alignment:'성향',background:'배경',target:'연결 세력',text:'관계 설명',url:'자료 주소'};
function collect(node,path,groupName,context=''){
 if(typeof node==='string'){const key=path.split('.').at(-1);if(['id','faction'].includes(key))return;fields.push({path,group:groupName,label:(context?context+' / ':'')+(labels[key]||key),image:key==='image',url:key==='url'});return;}
 if(Array.isArray(node)){node.forEach((v,i)=>{const itemLabel=v.title||v.name||v.target||v.label||String(i+1);collect(v,path+'.'+i,groupName,context?context+' · '+itemLabel:itemLabel);});return;}
 if(node&&typeof node==='object')Object.entries(node).forEach(([k,v])=>{if(k==='schemaVersion')return;collect(v,path?path+'.'+k:k,groupName,context);});
}
collect(data.meta,'meta','표지');collect(data.system,'system','체제');collect(data.history,'history','역사');collect(data.factions,'factions','세력');collect(data.characters,'characters','캐릭터');Object.keys(data.terms).forEach(t=>fields.push({path:'terms.'+t,group:'주석',label:t}));
fields.forEach(f=>{if(!groups.includes(f.group))groups.push(f.group);});
group.innerHTML=groups.map(x=>'<option>'+Guide.esc(x)+'</option>').join('');
const termSelect=document.querySelector('#term-select');termSelect.innerHTML=Object.keys(data.terms).map(t=>'<option>'+Guide.esc(t)+'</option>').join('');
function status(text,error=false){const el=document.querySelector('#status');el.textContent=text;el.classList.toggle('error',error);}
function selected(){return fields.find(x=>x.path===field.value);}
function showFields(path){field.innerHTML=fields.filter(x=>x.group===group.value).map(x=>'<option value="'+Guide.esc(x.path)+'">'+Guide.esc(x.label)+'</option>').join('');if(path)field.value=path;showValue();}
function showValue(){const f=selected();if(!f)return;value.value=Guide.get(data,f.path);document.querySelector('#value-label').textContent=f.image?'이미지 주소':f.url?'참고 자료 주소':'문구';value.rows=f.image||f.url?4:12;document.querySelector('#field-help').textContent=f.image?'인물 사진은 1470 × 640 비율로 전체가 보이게 표시됩니다. GitHub 파일 주소 또는 직접 이미지 주소를 넣으세요. 비워 두면 사진 자리를 남깁니다.':f.url?'http 또는 https로 시작하는 자료 주소를 입력하세요.':'줄을 바꾸면 문단이 나뉩니다. 주석은 [[용어]] 형식으로 넣을 수 있습니다.';document.querySelector('.annotation-insert').hidden=f.image||f.url||f.group==='주석';updateImage();sendPreview();}
function updateImage(){const box=document.querySelector('#image-preview'),f=selected();box.replaceChildren();box.hidden=!f?.image||!value.value;if(box.hidden)return;const url=Guide.imageURL(value.value);if(!url){box.textContent='이미지 주소 형식을 확인하세요.';return;}const img=document.createElement('img');img.src=url;img.alt='편집 중인 이미지';img.addEventListener('error',()=>{box.textContent='이미지를 불러오지 못했습니다. 공개된 직접 이미지 주소인지 확인하세요.';});box.append(img);}
function sendPreview(){try{Guide.validate(data);frame.contentWindow?.postMessage({type:'moscow-preview',content:data,path:field.value},location.origin);}catch(e){status(e.message,true);}}
function edit(){const f=selected();if(!f)return;Guide.set(data,f.path,value.value);dirty=true;status('저장하지 않은 수정 사항이 있습니다.');clearTimeout(previewTimer);previewTimer=setTimeout(()=>{sendPreview();updateImage();},220);}
function save(){data=Guide.save(data);dirty=false;status('이 브라우저에 초안을 저장했습니다. '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}));sendPreview();return{saved:true,scope:'current-browser'};}
group.addEventListener('change',()=>showFields());field.addEventListener('change',showValue);value.addEventListener('input',edit);
frame.addEventListener('load',sendPreview);
document.querySelector('#save').addEventListener('click',()=>{try{save();}catch(e){status(e.message,true);}});
document.querySelector('#export').addEventListener('click',()=>{try{const checked=Guide.validate(data),blob=new Blob([JSON.stringify(checked,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='moscow-handbook-v2-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('현재 수정 내용을 JSON으로 내려받았습니다. 이 채팅에 전달하면 사이트 전체에 반영할 수 있습니다.');}catch(e){status(e.message,true);}});
const file=document.querySelector('#file');document.querySelector('#import').addEventListener('click',()=>file.click());file.addEventListener('change',async()=>{const f=file.files[0];if(!f)return;try{if(f.size>2000000)throw new Error('2MB 이하의 V2 JSON 파일을 선택하세요.');const checked=Guide.validate(JSON.parse(await f.text()));if(dirty&&!confirm('저장하지 않은 수정을 가져온 JSON으로 바꿀까요?'))return;data=checked;dirty=true;showValue();status('JSON을 가져왔습니다. 내용을 확인한 뒤 초안을 저장하세요.');}catch(e){status('가져오지 못했습니다. '+e.message,true);}finally{file.value='';}});
document.querySelector('#reset').addEventListener('click',()=>{if(!confirm('이 브라우저의 초안을 지우고 게시된 원본으로 되돌릴까요? 필요한 수정은 먼저 JSON으로 내려받으세요.'))return;try{localStorage.removeItem(Guide.key);data=structuredClone(Guide.original);dirty=false;showValue();status('게시된 원본으로 복원했습니다.');}catch{status('브라우저 초안을 지우지 못했습니다.',true);}});
document.querySelector('#insert-term').addEventListener('click',()=>{const token='[['+termSelect.value+']]',start=value.selectionStart,end=value.selectionEnd;value.setRangeText(token,start,end,'end');value.focus();edit();});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key!==Guide.key)return;if(dirty){status('다른 창에서 초안이 바뀌었습니다. 현재 수정은 유지되며, 저장하면 이 내용으로 덮어씁니다.');return;}data=Guide.load();showValue();status('다른 창에서 저장한 초안을 불러왔습니다.');});
showFields();if(Guide.storageError)status(Guide.storageError,true);
const mc=document.modelContext;
if(mc?.registerTool){const lifecycle=new AbortController();const specs=[
{name:'read_handbook_fields',title:'가이드북 편집 항목 읽기',description:'Read editable handbook fields and their current staged text. Does not save or publish.',inputSchema:{type:'object',properties:{group:{type:'string',enum:groups}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input={}){if(input.group&&!groups.includes(input.group))throw new Error('Unknown group');return{fields:fields.filter(f=>!input.group||f.group===input.group).map(f=>({path:f.path,label:f.label,value:Guide.get(data,f.path)})),unsaved:dirty};}},
{name:'stage_handbook_edits',title:'가이드북 수정 미리보기',description:'Stage text or image URL edits and update the visible editor and preview. Does not save or publish.',inputSchema:{type:'object',properties:{edits:{type:'array',minItems:1,maxItems:100,items:{type:'object',properties:{path:{type:'string'},value:{type:'string'}},required:['path','value'],additionalProperties:false}}},required:['edits'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||!Array.isArray(input.edits)||input.edits.length<1||input.edits.length>100)throw new Error('Provide 1–100 edits');const next=structuredClone(data);for(const e of input.edits){if(!fields.some(f=>f.path===e.path)||typeof e.value!=='string')throw new Error('Unknown editable field');Guide.set(next,e.path,e.value);}data=Guide.validate(next);dirty=true;const last=fields.find(f=>f.path===input.edits.at(-1).path);group.value=last.group;showFields(last.path);status('수정 내용을 미리보기에 반영했습니다. 아직 저장하지 않았습니다.');return{staged:input.edits.length,saved:false};}},
{name:'save_handbook_browser_draft',title:'브라우저 초안 저장',description:'Save staged handbook edits in this browser only. Does not publish to the hosted website.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){return save();}}
];for(const spec of specs){try{Promise.resolve(mc.registerTool(spec,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
